"""empty message

Revision ID: 3f96349d692d
Revises: 9ed4c1a215b7
Create Date: 2025-01-26 18:04:58.439533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f96349d692d'
down_revision = '9ed4c1a215b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_balance', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('eth_balance', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('freezed_balance', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('freezed_balance')
        batch_op.drop_column('eth_balance')
        batch_op.drop_column('btc_balance')

    op.create_table('balance',
    sa.Column('balance_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('balance_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['balance_user_id'], ['user.user_id'], name='balance_ibfk_1'),
    sa.PrimaryKeyConstraint('balance_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
