"""empty message

Revision ID: 9ed4c1a215b7
Revises: 5b751413f83f
Create Date: 2025-01-26 18:00:44.047344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ed4c1a215b7'
down_revision = '5b751413f83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.drop_column('freezed_balance')
        batch_op.drop_column('eth_balance')
        batch_op.drop_column('btc_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_balance', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('eth_balance', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('freezed_balance', mysql.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
