"""empty message

Revision ID: acdff19593d1
Revises: af364acee157
Create Date: 2024-07-26 12:52:32.677797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acdff19593d1'
down_revision = 'af364acee157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('btc_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('eth_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('freezed_balance',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('balance_user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.alter_column('check_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('trans_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('trans_amount',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.alter_column('check_amount',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('balance_user_id',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('freezed_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('eth_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('btc_balance',
               existing_type=sa.String(length=64),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
